### ISSUE TITLE
Enable Multi-tenancy lockdown

### ISSUE THREAD

**Issue by souleb** [weaveworks/flux2-openshift#11]
Enable multi-tenancy lockdown as described in the [doc](https://fluxcd.io/docs/installation/#multi-tenancy-lockdown).

**Comment by blezoray** [comment]
After some tests, I don't see any solution to optionnaly configure multi-tenancy with OLM as the ClusterServiceVersion is not configurable.
Maybe you should enforce multi-tenancy as default because Openshift is mainly deployed with multi-tenancy ?

Rgds, Bruno.

**Comment by stefanprodan** [comment]
Me and Soule we've been working on a new operator that allows configuring Flux. See https://operatorhub.io/operator/flux-operator which supports multi-tenancy lockdown e.g.

```yaml
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: 1h
    fluxcd.controlplane.io/reconcileTimeout: 5m
spec:
  distribution:
    version: 2.3.x
    registry: ghcr.io/fluxcd
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
    - image-reflector-controller
    - image-automation-controller
  cluster:
    type: openshift
    multitenant: true
    networkPolicy: true
    domain: cluster.local
```
